# Generated by Django 3.1.3 on 2020-12-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201122_1659'),
        ('order', '0006_delete_productinorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(max_length=100, verbose_name='Quantity')),
                ('order', models.ManyToManyField(related_name='order', to='order.Order')),
                ('product', models.ManyToManyField(related_name='product', to='products.Product')),
            ],
        ),
    ]
