# Generated by Django 3.1.3 on 2020-12-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201122_1659'),
        ('order', '0007_productinorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='price',
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ManyToManyField(to='order.Order'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='quantity',
            field=models.IntegerField(max_length=100, verbose_name='Quantity'),
        ),
    ]
