# Generated by Django 3.1.3 on 2020-11-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainDishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('cover_photo', models.ImageField(upload_to='', verbose_name='Photo')),
                ('price', models.DecimalField(decimal_places=5, max_digits=5, verbose_name='Price')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Updated Date')),
                ('quantity', models.PositiveIntegerField(max_length=5, verbose_name='Amount')),
                ('weight', models.PositiveIntegerField(max_length=5, verbose_name='Weight')),
                ('ingredients', models.CharField(max_length=200, verbose_name='Ingredients')),
            ],
        ),
    ]
