# Generated by Django 3.1.3 on 2020-11-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201117_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindishes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price'),
        ),
    ]
