# Generated by Django 3.1.3 on 2020-11-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201117_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainDish',
            new_name='Products',
        ),
    ]
