# Generated by Django 3.1.3 on 2020-11-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201117_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('Main dish', 'Main dish'), ('Desert', 'Desert'), ('Drink', 'Drink'), ('Other products', 'Other products')], default='Main dish', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ingredients'),
        ),
    ]
