# Generated by Django 3.1.3 on 2020-11-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201117_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('main_dish', 'Main dish'), ('desert', 'Desert'), ('drink', 'Drink'), ('other_products', 'Other products')], default='Main dish', max_length=50),
        ),
    ]
